language: python
sudo: false

python:
  - "2.7"
  - "3.4"

notifications:
  email: false

before_install: # Setup anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install: # Install packages
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas scikit-learn statsmodels
  # Coverage packages are on my binstar channel
  - "pip install python-coveralls"
  - "pip install coverage"
  - "pip install -r requirements.txt"

script: # Run test
  - nosetests tests --with-coverage

after_success: # Calculate coverage
  - coveralls --config_file .coveragerc
